---
title: "Course Calendar and Materials"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
---

Each week, Tuesdays will be primarily lecture and class discussion or short activities, and Thursdays will be lab days.

* **You should bring your laptop with you to every class period.**
* Assigned readings for the week should be completed prior to lab. Whether you learn better by reading prior to lecture, or hearing a lecture prior to reading is up to you.
* Weekly labs are due in GitHub by 5pm on the due date (typically Wednesdays).
* Weekly homework assignments are due in D2L by 5pm on the due date (typically Wednesdays).


---

## Week 1 (Jan 19--21): Course Overview

---

__Weekly Overview:__ 

1. Discuss course structure and expectations.
1. Install R and RStudio.
1. Provide a brief introduction to R.

__Reading and Online Resources:__ 

- Intro to R:
  * [Modern Dive Ch. 1](https://moderndive.com/1-getting-started.html)
  * [R 4 DS Ch. 1](https://r4ds.had.co.nz/introduction.html)
- R Installation Resources: 
  * [Guide from Earth Lab](https://www.earthdatascience.org/courses/earth-analytics/document-your-science/setup-r-rstudio/)
  * [Guide from DataCamp](https://www.datacamp.com/community/tutorials/installing-R-windows-mac-ubuntu)
- R Markdown: 
  * [R Markdown Overview](https://rmarkdown.rstudio.com/lesson-1.html)

__In-class Materials:__

- [Week 1 slides](lectures/week1/week1-slides.pdf)


---

## Week 2 (Jan 24--28): Version Control with Git

---

__Weekly Overview:__ 

1. Create a Github account.
1. Install Git.
1. Connect RStudio to Git and GitHub.
1. Provide a brief introduction to version control with Git.

  
__Reading and Online Resources:__ 

- Happy Git with R:
  * [Ch. 1](https://happygitwithr.com/big-picture.html) - Big picture
  * [Ch. 4](https://happygitwithr.com/github-acct.html) - Create a GitHub account
  * [Ch. 6](https://happygitwithr.com/install-git.html) - Install Git
  * [Ch. 7](https://happygitwithr.com/hello-git.html), [Ch. 9](https://happygitwithr.com/https-pat.html), [Ch. 11](https://happygitwithr.com/push-pull-github.html), [Ch. 12](https://happygitwithr.com/rstudio-git-github.html) - Configure Git, GitHub, and RStudio


__In-class Materials:__

- Week 2 slides ([PDF](lectures/week2/week2-slides.pdf)) ([Rmd](lectures/week2/week2-slides.Rmd))

__In-class Lab:__

- [Lab 1](labs/lab-01/lab-01-hello-r.html) - Due Monday, Jan 31 by 5pm in GitHub

__Homework:__

- [Homework 1](homework/hw-01/hw01.html) ([Rmd](homework/hw-01/hw01.Rmd)) - Due Tuesday, Feb 1 by 5pm in D2L

_Note_: In order for RStudio to compile to a PDF document, you need some version of TeX installed on your system. An easy way to install the TeX required for R Markdown compilation to PDF files is through the `tinytex` package.

- [Video instructions for installing TeX through `tinytex`](https://www.youtube.com/watch?v=HwzE2okhq-M)
- [`tinytex` R package website](https://yihui.org/tinytex/)

---

## Week 3 (Jan 31--Feb 4): Data Visualization with ggplot2

---

__Weekly Overview:__ 

1. Understand R data structures and basic "base R" graphics functions (leftover from last week).
1. Describe the "grammar of graphics".
1. Visualize data with the `ggplot2` package.
 
__Reading and Online Resources:__ 

* [Modern Dive Ch. 2](https://moderndive.com/2-viz.html)
* [R 4 DS Ch. 3](https://r4ds.had.co.nz/data-visualisation.html)
* [`ggplot2` website + cheatsheet](https://ggplot2.tidyverse.org/)
* Extra reference: [Data Carpentry `ggplot2` tutorial](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html)

__In-class Materials:__

- Week 3 slides ([PDF](lectures/week3/week3-slides.pdf)) ([Rmd](lectures/week3/week3-slides.Rmd))

__In-class Lab:__

- [Lab 2](labs/lab-02/lab-02-plastic-waste.html) - Due Monday, Feb 7 by 5pm in GitHub

__Homework:__

- [Homework 2](homework/hw-02/hw-02-airbnb-edi.html) ([Rmd](homework/hw-02/hw-02.Rmd)) - Due Tuesday, Feb 8 by 5pm in D2L

---

## Week 4 (Feb 7--11): Data Transformation with the Tidyverse

---

__Weekly Overview:__ 

1. Practice wrangling data with the tidyverse "verbs": `filter()`, `arrange()`,
`select()`, `mutate()`, `group_by()`, `summarise()`
 
__Reading and Online Resources:__ 


- [Modern Dive Ch. 3](https://moderndive.com/3-wrangling.html)
- [R 4 DS Ch. 5](https://r4ds.had.co.nz/transform.html) and [Ch. 10](https://r4ds.had.co.nz/tibbles.html)
- Extra reference: [Data Carpentry `dplyr` and `tidyr` tutorial](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html)
    

__In-class Materials:__

- [Week 4 slides](lectures/week4/week4-slides.html) ([Rmd](lectures/week4/week4-slides.Rmd)) ([PDF](lectures/week4/week4-slides.pdf))

__In-class Lab:__

- [Lab 3 Prep](labs/lab-03/lab-03-prep.html) - Complete this prior to the start of class on Thursday Feb 10!
- [Lab 3](labs/lab-03/lab-03-nobel-laureates.html) - Due Monday, Feb 14 by 5pm in GitHub


 
__Homework:__

- [Homework 3](homework/hw-03/hw-03-college-majors.html) ([Rmd](homework/hw-03/hw-03.Rmd)) - Due **Wednesday**, Feb 16 by 5pm in D2L

---

## Week 5 (Feb 14--18): R Overview and Style

---

__Weekly Overview:__ 

1. Write code using tidyverse style guidelines
2. Practice debugging code
3. Write your own R functions
 
__Reading and Online Resources:__ 

- R Style:
    * [R style guide](http://adv-r.had.co.nz/Style.html)
    * [Google's R style guide](https://google.github.io/styleguide/Rguide.html)
    * Browse through Chapters 1--5 of [The tidyverse style guide](https://style.tidyverse.org/index.html)
- Workflow and organization in R:
    * [R 4 DS Ch. 4](https://r4ds.had.co.nz/workflow-basics.html): Basics
    * [R 4 DS Ch. 6](https://r4ds.had.co.nz/workflow-scripts.html): Scripts
    * [R 4 DS Ch. 8](https://r4ds.had.co.nz/workflow-projects.html): Projects


__In-class Materials:__

- [Week 5 slides](lectures/week5/week5-slides.html) ([Rmd](lectures/week5/week5-slides.Rmd)) ([PDF](lectures/week5/week5-slides.pdf))

__In-class Lab:__

- [Lab 4](labs/lab-04/lab-04-review.html) - Due **Tuesday**, Feb 22 by 5pm in GitHub

__Homework:__

- [Homework 4](homework/hw-04/hw-04-style.html) ([Rmd](homework/hw-04/hw-04.Rmd)) - Due **Friday**, **Mar 4** by 5pm in D2L 

---

## Week 6 (Feb 21--25): Functions, Loops and Debugging

---

__Weekly Overview:__ 

1. Write your own R functions (cont)
2. Use for/while loops in simulation
3. Debug using built-in tools
 
__Reading and Online Resources:__ 

- [R 4 DS Ch. 19](https://r4ds.had.co.nz/functions.html): Functions
- [R 4 DS Ch. 21](https://r4ds.had.co.nz/iteration.html): Iterations (Sections 21.0--21.3)
- Debugging:
    * [Debugging in RStudio](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio)
    * [Roger Peng's Debugging Guide](http://www.biostat.jhsph.edu/~rpeng/docs/R-debug-tools.pdf) (optional/advanced)
    * [Video on debugging](https://montana.techsmithrelay.com/6guK) (Dr. Hoegh)

__In-class Materials:__

- [Week 6 slides](lectures/week6/week6-slides.html)  ([Rmd](lectures/week6/week6-slides.Rmd)) ([PDF](lectures/week6/week6-slides.pdf))

__**Midterm Exam 1:**__

- Midterm Exam 1 will cover material from Weeks 1--4: 
  * Overview of R and RStudio
  * Version control with Git and GitHub
  * Data visualization with `ggplot2`
  * Data wrangling with `tidyverse` (specifically, `dplyr`)
  * Labs 1--4 and homeworks 1--3
- In-class component on Thursday, Feb 24
- Take-home component due in D2L Monday, Feb 28 by 5:00pm
- [Examples of old exams](https://github.com/stat408/oldexams)



---

## Week 7 (Feb 28--Mar 4): Data Wrangling 1 -- Tidy Data and Relational Data


---

__Weekly Overview:__ 

1. Implement merge and join procedures to wrangle multiple data sets
2. Transform data from wide to long format
 
__Reading and Online Resources:__ 

- [Modern Dive Ch. 4](https://moderndive.com/4-tidy.html)
- [R 4 DS Ch. 12](https://r4ds.had.co.nz/tidy-data.html): Tidy data
- [R 4 DS Ch. 13](https://r4ds.had.co.nz/relational-data.html): Relational data


__In-class Materials:__

- [Week 7 slides](lectures/week7/week7-slides.html)
- [Week 7 slides repo](https://github.com/stat408-s22/week7-slides)


__In-class Lab:__

- [Lab 5](labs/lab-05/lab-05-wrangling.html) - Due Monday, Mar 7 by 5pm in GitHub

__Homework:__

- [Homework 5](homework/hw-05/hw-05-wrangle.html) ([Rmd](homework/hw-05/hw-05.Rmd)) - Due Tuesday, Mar 8 by 5pm in D2L



---

## Week 8 (Mar 7--11): Data Wrangling 2 -- Strings, Factors, Date/Time

---

__Weekly Overview:__ 

1. Continue to learn data wrangling techniques
2. Manipulate character strings
3. Manipulate time/date objects
4. Manipulate factor objects

__Reading and Online Resources:__ 

- Strings: ([R 4 DS Ch. 14](https://r4ds.had.co.nz/strings.html))
- Factors: ([R 4 DS Ch. 15](https://r4ds.had.co.nz/factors.html))
- Dates and Times: ([R 4 DS Ch.16](https://r4ds.had.co.nz/dates-and-times.html))
- Tidyverse packages:
    * [stringr website](https://stringr.tidyverse.org/)
    * [forcats website](https://forcats.tidyverse.org/)
    * [lubridate website](https://lubridate.tidyverse.org/)

__In-class Materials:__

- [Week 8 slides](lectures/week8/week8-slides.html)
- [Week 8 slides exercises](lectures/week8/week8-exercises.Rmd)
- [Martian Alphabet Activity](lectures/week8/MartianAlphabetActivity.html) ([Rmd](lectures/week8/MartianAlphabetActivity.Rmd)) (updated with notes from class)
    * [R Console from class](lectures/week8/MartianAlphabetActivity-RConsole.txt)
 
__Homework:__

- [Homework 6](homework/hw-06/hw-06.html) ([Rmd](homework/hw-06/hw-06.Rmd)) - Due Thursday, Mar 24 by 11pm in D2L


---

## Spring Break (Mar 14--18)

---

- No class

---

## Week 9 (Mar 21--25): Web Scraping

---

__Weekly Overview:__ 

1. Understand the basic structure of HTML
2. Use the `rvest` package to scrape data from the web
3. Explore using functions and iteration applied to web scraping

__Reading and Online Resources:__ 

- [Web scraping with `rvest`](https://rvest.tidyverse.org/articles/rvest.html)
- [SelectorGadget vignette](https://cran.r-project.org/web/packages/rvest/vignettes/selectorgadget.html)

__In-class Materials:__

- [Week 9 slides](lectures/week9/week9-slides.html) ([Rmd](lectures/week9/week9-slides.Rmd))
- [IMDB R script from class](lectures/week9/imdb.R)
 
__In-class Lab:__

- [Lab 6](labs/lab-06/lab-06-uoe-art.html) - Due Wednesday, Mar 30 by 5pm in GitHub

__Homework:__

- No homework this week due to a longer Lab 6.


---

## Week 10 (Mar 28--Apr 1): Data Visualization Principles + R Shiny Dashboards

---

__Weekly Overview:__ 

1. Understand and implement principles of data visualization
2. Develop a beginner understanding of R Shiny
3. Introduce data visualization project and select data set

__Reading and Online Resources:__ 

- [R Shiny Tutorial](https://shiny.rstudio.com/tutorial/) - great info here, including a series of videos
- [R Shiny Cheatsheet](https://shiny.rstudio.com/images/shiny-cheatsheet.pdf)
- [10 Data Viz Practices for the Web (or Elsewhere)](https://www.webdesignerdepot.com/2018/07/10-data-visualization-best-practices-for-the-web/)

__In-class Materials:__

- [Week 10 slides](lectures/week10/week10-slides.html) ([Rmd](lectures/week10/week10-slides.Rmd))
- [Shiny tutorial Rmd file](lectures/week10/week10-shiny-tutorial.Rmd)

__In-class Lab:__

- [Lab 7](labs/lab-07/lab-07-shiny.html) - Due Wednesday, Apr 6 by 5pm in GitHub


__Homework:__

- [Homework 7](homework/hw-07/hw-07.pdf) ([Rmd](homework/hw-07/hw-07.Rmd)) - Due Wednesday, Apr 6 by 11pm in D2L


---

## Week 11 (Apr 4--8): Modeling Uncertainty

---

__Weekly Overview:__ 

1. Explore sampling variability through simulation.
2. Carry out bootstrapping techniques to estimate sampling variability.

__Reading and Online Resources:__ 

- Sampling: [Modern Dive Ch. 7](https://moderndive.com/7-sampling.html)
- Bootstrapping: [Modern Dive Ch. 8](https://moderndive.com/8-confidence-intervals.html)

__In-class Materials:__

- [Week 11 slides](lectures/week11/week11-slides.html) ([Rmd](lectures/week11/week11-slides.Rmd))
- [Bootstrapping R script from class](lectures/week11/Slope_Bootstrapping.R)


__In-class Lab:__

- [Lab 8](labs/lab-08/lab-08-inference-smoking.html) - Due Wednesday, Apr 13 by 5pm in GitHub

__Homework:__

- [Homework 8](homework/hw-08/hw-08.pdf) ([Rmd](homework/hw-08/hw-08.Rmd)) - Due Wednesday, Apr 13 by 11pm in D2L

__Project:__

By April 8th at 11:00 p.m., the following must be completed and available in your Github repo:

1. Topic you are interested in researching (in README.md)
2. Data source (in README.md)
3. Two research questions (in README.md) 
4. R script that scrapes a data set of interest (scrape.R)
5. Scraped and cleaned data set (in the data folder) 

---

## Week 12 (Apr 11--15): Review

---

__Weekly Overview:__ 

1. Review and practice important concepts in statistical computing and visualization using R.


__In-class Materials:__


__**Midterm Exam 2:**__

- Midterm Exam 2 will cover material from Weeks 5--10
- In-class component on Thursday, Apr 14
- Take-home component due in D2L Monday, Apr 18 by 5:00pm
- [Examples of old exams](https://github.com/stat408/oldexams)



---

## Week 13 (Apr 18--22): SAS I

---

__Weekly Overview:__ 

1. Install SAS OnDemand
2. SAS basics and DATA steps

 
__Reading and Online Resources:__ 

- SAS registration info (will post soon)
- [SAS login link](https://welcome.oda.sas.com/login)
- SAS video resources:
    * [Create a SAS Profile](https://video.sas.com/detail/video/4567854444001/sas-ondemand-for-academics:-profile-creation-student-edition)
    * [Enrolling in SAS Course](https://video.sas.com/detail/video/4567828824001/sas-ondemand-for-academics:-enrollment-link-student-edition)

__In-class Materials:__


__In-class Lab:__

 
__Homework:__


__Project:__

By April 22th at 11:00 p.m., the following must be completed:

1. RShiny dashboard R code completed in GitHub
2. RShiny app deployed to [https://www.shinyapps.io/](https://www.shinyapps.io/)
3. Link to RShiny app posted in D2L Project Shiny Apps discussion board



---

## Week 14 (Apr 25--29): SAS II

---

__Weekly Overview:__ 

1. Overview of SAS PROCS
2. Introduction to PROC SQL

__Reading and Online Resources:__ 



__In-class Materials:__


__In-class Lab:__

 
__Homework:__


---

## Week 15 (May 2--6): SAS III

---

__Weekly Overview:__ 

1. Graphics in SAS
2. Semester review

__Reading and Online Resources:__ 



__In-class Materials:__


__In-class Lab:__

 
__Project:__

By May 6th at 11:00 p.m., the following must be completed:

1. Post comments on at least **two** RShiny app discussion post including at (a) least one feature you think works well, and (b) at least one feature that you might have done differently, and (c) how you could extend the study (e.g., what other research questions does the analysis inspire?).

---

## Final Exam 

---

**In Class portion:** Tuesday, May 10 12:00--1:50pm

**Take Home portion:** Due Monday, May 9 by 5:00pm
