---
title: "Team Agreement"
author: |
        | Insert team name here:
        | Insert team member 1 here
        | Insert team member 2 here
        | Insert team member 3 here
        | Insert team member 4 here
date: "`r Sys.Date()`"
output: pdf_document
---

## Instructions 
Discuss each of the items below as a team. Have one person act as the
recorder and type the team's decisions in this document under each item. 
*Be sure the team agrees on an item before it is added to the document.*
Once the document is complete, the recorder should knit, commit,
and push the team agreement to GitHub. All team members can refer
to this document throughout the semester. 
*This document does not need to be submitted on D2L.*

## Team expectations 

### Weekly meetings
*Identify a 1--2 hour weekly block outside of lab where the team
can meet to work on assignments. All team members should block
off this time on their calendar in case the group needs to meet
to finish lab or work on the project.* 


### Meeting "location" and virtual meeting space
*How the team will meet to work together (e.g., in-person, Zoom,
Microsoft Teams, Google Hangouts). Be sure every member is able to
access the virtual meeting space. This virtual meeting space can also be used if a team member needs to join lab remotely.*


### If you are unable to find a weekly time when the team can meet, briefly outline a plan to work on assignments outside of lab. Otherwise, you can delete this item.


### Primary method of communication
*The team's primary method of communication outside of
meetings (e.g. GitHub discussions, GroupMe, Slack, text messages, etc.)*


### How should someone notify the other members if they are unable to attend lab or a scheduled team meeting?


### By when should everyone have their portion of the lab completed?
*Keep in mind your team may want to have time to review
the lab before turning it in to make sure it is a cohesive write up.* 


### Any other items the team would like to discuss or plan. 




